
const WORDS_A1 = [
  { en: "your", uk: "твій / ваш" },
  { en: "dog", uk: "собака" },
  { en: "cat", uk: "кіт" },
  { en: "house", uk: "дім" },
  { en: "moon", uk: "місяць" },
  { en: "flower", uk: "квітка" },
  { en: "car", uk: "машина" },
  { en: "bus", uk: "автобус" },
  { en: "boy", uk: "хлопчик" },
  { en: "girl", uk: "дівчинка" },
  { en: "father", uk: "тато" },
  { en: "brother", uk: "брат" },
  { en: "day", uk: "день" },
  { en: "hour", uk: "година" },
  { en: "food", uk: "їжа" },
  { en: "tea", uk: "чай" },
  { en: "coffee", uk: "кава" },
  { en: "fish", uk: "риба" },
  { en: "rice", uk: "рис" },
  { en: "egg", uk: "яйце" },
  { en: "cheese", uk: "сир" },
  { en: "sugar", uk: "цукор" },
  { en: "salt", uk: "сіль" },
  { en: "soup", uk: "суп" },
  { en: "tomato", uk: "помідор" },
  { en: "onion", uk: "цибуля" },
  { en: "banana", uk: "банан" },
  { en: "lemon", uk: "лимон" },
  { en: "strawberry", uk: "полуниця" },
  { en: "grape", uk: "виноград" },
  { en: "pear", uk: "груша" },
  { en: "peach", uk: "персик" },
  { en: "juice", uk: "сік" },
  { en: "butter", uk: "масло" },
  { en: "cake", uk: "торт" },
  { en: "bread roll", uk: "булочка" },
  { en: "cookie", uk: "печиво" },
  { en: "breakfast", uk: "сніданок" },
  { en: "dinner", uk: "вечеря" },
  { en: "kitchen", uk: "кухня" },
  { en: "bathroom", uk: "ванна" },
  { en: "bed", uk: "ліжко" },
  { en: "wall", uk: "стіна" },
  { en: "ceiling", uk: "стеля" },
  { en: "garden", uk: "сад" },
  { en: "hotel", uk: "готель" },
  { en: "bank", uk: "банк" },
  { en: "airport", uk: "аеропорт" },
  { en: "city", uk: "місто" },
  { en: "country", uk: "держава" },
  { en: "language", uk: "мова" },
  { en: "English", uk: "англійська" },
  { en: "Ukrainian", uk: "українська" },
  { en: "surname", uk: "прізвище" },
  { en: "address", uk: "адреса" },
  { en: "email", uk: "електронна пошта" },
  { en: "color", uk: "колір" },
  { en: "red", uk: "червоний" },
  { en: "blue", uk: "синій" },
  { en: "green", uk: "зелений" },
  { en: "black", uk: "чорний" },
  { en: "brown", uk: "коричневий" },
  { en: "pink", uk: "рожевий" },
  { en: "gray", uk: "сірий" },
  { en: "clothes", uk: "одяг" },
  { en: "shirt", uk: "сорочка" },
  { en: "dress", uk: "сукня" },
  { en: "skirt", uk: "спідниця" },
  { en: "trousers", uk: "штани" },
  { en: "jeans", uk: "джинси" },
  { en: "shoes", uk: "взуття" },
  { en: "boots", uk: "чоботи" },
  { en: "hat", uk: "капелюх" },
  { en: "coat", uk: "пальто" },
  { en: "jacket", uk: "куртка" },
  { en: "socks", uk: "шкарпетки" },
  { en: "gloves", uk: "рукавички" },
  { en: "glasses", uk: "окуляри" },
  { en: "ticket", uk: "квиток" },
  { en: "key", uk: "ключ" },
  { en: "door", uk: "двері" },
  { en: "floor", uk: "поверх/підлога" },
  { en: "stairs", uk: "сходи" },
  { en: "bedroom", uk: "спальня" },
  { en: "living room", uk: "вітальня" },
  { en: "toilet", uk: "туалет" },
  { en: "mirror", uk: "дзеркало" },
  { en: "lamp", uk: "лампа" },
  { en: "computer", uk: "комп’ютер" },
  { en: "laptop", uk: "ноутбук" },
  { en: "mouse", uk: "мишка" },
  { en: "keyboard", uk: "клавіатура" },
  { en: "screen", uk: "екран" },
  { en: "TV", uk: "телевізор" },
  { en: "camera", uk: "камера" },
  { en: "game", uk: "гра" },
  { en: "football", uk: "футбол" },
  { en: "basketball", uk: "баскетбол" },
  { en: "tennis", uk: "теніс" },
  { en: "swimming", uk: "плавання" },
  { en: "play", uk: "грати" },
  { en: "eat", uk: "їсти" },
  { en: "drink", uk: "пити" },
  { en: "buy", uk: "купувати" },
  { en: "help", uk: "допомагати" },
  { en: "doctor", uk: "лікар" },
  { en: "driver", uk: "водій" },
  { en: "worker", uk: "робітник" },
  { en: "farmer", uk: "фермер" },
  { en: "pupil", uk: "учень" },
  { en: "friend", uk: "друг" },
  { en: "baby", uk: "немовля" },
  { en: "child", uk: "дитина" },
  { en: "parents", uk: "батьки" },
  { en: "grandmother", uk: "бабуся" },
  { en: "grandfather", uk: "дідусь" },
  { en: "aunt", uk: "тітка" },
  { en: "uncle", uk: "дядько" },
  { en: "cousin", uk: "двоюрідний брат/сестра" },
  { en: "family", uk: "сім’я" },
  { en: "hand", uk: "рука" },
  { en: "head", uk: "голова" },
  { en: "eye", uk: "око" },
  { en: "ear", uk: "вухо" },
  { en: "face", uk: "обличчя" },
  { en: "hair", uk: "волосся" },
  { en: "leg", uk: "нога" },
  { en: "foot", uk: "ступня" },
  { en: "back", uk: "спина" },
  { en: "stomach", uk: "живіт" },
  { en: "tooth", uk: "зуб" },
  { en: "heart", uk: "серце" },
  { en: "body", uk: "тіло" },
  { en: "health", uk: "здоров’я" },
  { en: "hospital", uk: "лікарня" },
  { en: "pain", uk: "біль" },
  { en: "cold", uk: "застуда/холодний" },
  { en: "hot", uk: "гарячий" },
  { en: "cool", uk: "прохолодний" },
  { en: "hungry", uk: "голодний" },
  { en: "thirsty", uk: "спраглий" },
  { en: "tired", uk: "втомлений" },
  { en: "angry", uk: "злий" },
  { en: "afraid", uk: "наляканий" },
  { en: "big", uk: "великий" },
  { en: "young", uk: "молодий" },
  { en: "good", uk: "добрий/хороший" },
  { en: "bad", uk: "поганий" },
  { en: "beautiful", uk: "красивий" },
  { en: "ugly", uk: "потворний" },
  { en: "easy", uk: "легкий" },
  { en: "difficult", uk: "важкий/складний" },
  { en: "fast", uk: "швидкий" },
  { en: "high", uk: "високий" },
  { en: "left", uk: "ліво" },
  { en: "closed", uk: "закритий" },
  { en: "clean", uk: "чистий" },
  { en: "dirty", uk: "брудний" },
  { en: "full", uk: "повний" },
  { en: "empty", uk: "порожній" },
  { en: "weak", uk: "слабкий" },
  { en: "interesting", uk: "цікавий" },
  { en: "boring", uk: "нудний" },
  { en: "important", uk: "важливий" },
  { en: "famous", uk: "відомий" },
  { en: "different", uk: "інший/різний" },
  { en: "false", uk: "неправдивий" },
  { en: "happy", uk: "радісний" },
  { en: "free", uk: "вільний/безкоштовний" },
  { en: "busy", uk: "зайнятий" },
  { en: "class", uk: "клас" },
  { en: "homework", uk: "домашнє завдання" },
  { en: "book", uk: "книга" },
  { en: "notebook", uk: "зошит" },
  { en: "eraser", uk: "гумка" },
  { en: "ruler", uk: "лінійка" },
  { en: "bag", uk: "портфель/сумка" },
  { en: "desk", uk: "парта" },
  { en: "chair", uk: "стілець" },
  { en: "exam", uk: "екзамен" },
  { en: "mark", uk: "оцінка" },
  { en: "university", uk: "університет" },
  { en: "college", uk: "коледж" },
  { en: "library", uk: "бібліотека" },
  { en: "math", uk: "математика" },
  { en: "history", uk: "історія" },
  { en: "geography", uk: "географія" },
  { en: "biology", uk: "біологія" },
  { en: "physics", uk: "фізика" },
  { en: "chemistry", uk: "хімія" },
  { en: "art", uk: "мистецтво" },
  { en: "teacher’s room", uk: "вчительська" },
  { en: "blackboard", uk: "дошка" },
  { en: "chalk", uk: "крейда" },
  { en: "lesson plan", uk: "план уроку" },
  { en: "dictionary", uk: "словник" },
  { en: "letter", uk: "літера/лист" },
  { en: "alphabet", uk: "алфавіт" },
  { en: "text", uk: "текст" },
  { en: "learn", uk: "вчитися" },
  { en: "know", uk: "знати" },
  { en: "forget", uk: "забувати" },
  { en: "ask", uk: "питати" },
  { en: "answer", uk: "відповідати" },
  { en: "explain", uk: "пояснювати" },
  { en: "finish", uk: "закінчувати" },
  { en: "close", uk: "закривати" },
  { en: "hate", uk: "ненавидіти" },
  { en: "can", uk: "вміти/могти" },
  { en: "afternoon", uk: "післяобідній час" },
  { en: "evening", uk: "вечір" },
  { en: "light", uk: "світло" },
  { en: "like", uk: "подобатися" },
  { en: "line", uk: "лінія" },
  { en: "list", uk: "список" },
  { en: "listen", uk: "слухати" },
  { en: "little", uk: "маленький" },
  { en: "live", uk: "жити" },
  { en: "long", uk: "довгий" },
  { en: "look", uk: "дивитися" },
  { en: "lose", uk: "втрачати" },
  { en: "lot", uk: "багато" },
  { en: "love", uk: "любити" },
  { en: "low", uk: "низький" },
  { en: "lunch", uk: "обід" },
  { en: "machine", uk: "машина" },
  { en: "main", uk: "головний" },
  { en: "make", uk: "робити" },
  { en: "man", uk: "чоловік" },
  { en: "many", uk: "багато" },
  { en: "map", uk: "карта" },
  { en: "market", uk: "ринок" },
  { en: "married", uk: "одружений" },
  { en: "match", uk: "матч / поєднувати" },
  { en: "material", uk: "матеріал" },
  { en: "matter", uk: "справа / мати значення" },
  { en: "may", uk: "можливо / травень" },
  { en: "meal", uk: "їжа / прийом їжі" },
  { en: "mean", uk: "означати" },
  { en: "meat", uk: "м’ясо" },
  { en: "medicine", uk: "ліки" },
  { en: "meet", uk: "зустрічати" },
  { en: "meeting", uk: "зустріч" },
  { en: "member", uk: "член (групи)" },
  { en: "message", uk: "повідомлення" },
  { en: "metal", uk: "метал" },
  { en: "middle", uk: "середина" },
  { en: "might", uk: "можливо" },
  { en: "mile", uk: "миля" },
  { en: "milk", uk: "молоко" },
  { en: "million", uk: "мільйон" },
  { en: "mind", uk: "розум / зважати" },
  { en: "minute", uk: "хвилина" },
  { en: "miss", uk: "сумувати / міс" },
  { en: "mistake", uk: "помилка" },
  { en: "modern", uk: "сучасний" },
  { en: "moment", uk: "момент" },
  { en: "money", uk: "гроші" },
  { en: "month", uk: "місяць" },
  { en: "more", uk: "більше" },
  { en: "morning", uk: "ранок" },
  { en: "most", uk: "найбільший / більшість" },
  { en: "mother", uk: "мати" },
  { en: "mountain", uk: "гора" },
  { en: "mouth", uk: "рот" },
  { en: "move", uk: "рухатися" },
  { en: "movie", uk: "фільм" },
  { en: "much", uk: "багато" },
  { en: "music", uk: "музика" },
  { en: "must", uk: "повинен" },
  { en: "name", uk: "ім’я" },
  { en: "narrow", uk: "вузький" },
  { en: "nation", uk: "нація" },
  { en: "natural", uk: "природний" },
  { en: "nature", uk: "природа" },
  { en: "near", uk: "біля / близько" },
  { en: "neck", uk: "шия" },
  { en: "need", uk: "потребувати" },
  { en: "neighbor", uk: "сусід" },
  { en: "never", uk: "ніколи" },
  { en: "new", uk: "новий" },
  { en: "news", uk: "новини" },
  { en: "newspaper", uk: "газета" },
  { en: "next", uk: "наступний" },
  { en: "nice", uk: "гарний / приємний" },
  { en: "night", uk: "ніч" },
  { en: "nine", uk: "дев’ять" },
  { en: "no", uk: "ні" },
  { en: "nobody", uk: "ніхто" },
  { en: "north", uk: "північ" },
  { en: "nose", uk: "ніс" },
  { en: "not", uk: "не" },
  { en: "note", uk: "нотатка / нота" },
  { en: "nothing", uk: "нічого" },
  { en: "notice", uk: "повідомлення / помічати" },
  { en: "now", uk: "зараз" },
  { en: "number", uk: "номер" },
  { en: "nurse", uk: "медсестра" },
  { en: "object", uk: "предмет" },
  { en: "ocean", uk: "океан" },
  { en: "of", uk: "з / про" },
  { en: "off", uk: "вимкнено / поза" },
  { en: "offer", uk: "пропонувати" },
  { en: "office", uk: "офіс" },
  { en: "often", uk: "часто" },
  { en: "oil", uk: "олія / нафта" },
  { en: "old", uk: "старий" },
  { en: "on", uk: "на" },
  { en: "once", uk: "один раз" },
  { en: "one", uk: "один" },
  { en: "only", uk: "тільки" },
  { en: "open", uk: "відкривати" },
  { en: "opposite", uk: "навпроти / протилежний" },
  { en: "or", uk: "або" },
  { en: "orange", uk: "апельсин / помаранчевий" },
  { en: "order", uk: "замовлення / порядок" },
  { en: "other", uk: "інший" },
  { en: "our", uk: "наш" },
  { en: "out", uk: "зовні" },
  { en: "outside", uk: "зовні" },
  { en: "over", uk: "над / через" },
  { en: "own", uk: "власний" },
  { en: "page", uk: "сторінка" },
  { en: "paint", uk: "фарбувати" },
  { en: "pair", uk: "пара" },
  { en: "paper", uk: "папір" },
  { en: "parent", uk: "батько/мати" },
  { en: "park", uk: "парк" },
  { en: "part", uk: "частина" },
  { en: "partner", uk: "партнер" },
  { en: "party", uk: "вечірка" },
  { en: "pass", uk: "проходити / здавати" },
  { en: "past", uk: "минулий / повз" },
  { en: "pay", uk: "платити" },
  { en: "pen", uk: "ручка" },
  { en: "pencil", uk: "олівець" },
  { en: "people", uk: "люди" },
  { en: "percent", uk: "відсоток" },
  { en: "perfect", uk: "ідеальний" },
  { en: "period", uk: "період" },
  { en: "person", uk: "особа" },
  { en: "phone", uk: "телефон" },
  { en: "photo", uk: "фото" },
  { en: "photograph", uk: "фотографія" },
  { en: "phrase", uk: "фраза" },
  { en: "physical", uk: "фізичний" },
  { en: "pick", uk: "вибирати" },
  { en: "picture", uk: "картина / зображення" },
  { en: "piece", uk: "шматок / частина" },
  { en: "place", uk: "місце" },
  { en: "plant", uk: "рослина / завод" },
  { en: "player", uk: "гравець" },
  { en: "please", uk: "будь ласка" },
  { en: "point", uk: "точка / вказувати" },
  { en: "police", uk: "поліція" },
  { en: "pool", uk: "басейн" },
  { en: "poor", uk: "бідний" },
  { en: "popular", uk: "популярний" },
  { en: "position", uk: "позиція" },
  { en: "possible", uk: "можливий" },
  { en: "post", uk: "пошта / повідомлення" },
  { en: "potato", uk: "картопля" },
  { en: "pound", uk: "фунт" },
  { en: "practice", uk: "практика" },
  { en: "prepare", uk: "готувати" },
  { en: "present", uk: "подарунок / теперішній" },
  { en: "pretty", uk: "гарненький" },
  { en: "price", uk: "ціна" },
  { en: "probably", uk: "мабуть" },
  { en: "problem", uk: "проблема" },
  { en: "produce", uk: "виробляти" },
  { en: "product", uk: "продукт" },
  { en: "program", uk: "програма" },
  { en: "project", uk: "проєкт" },
  { en: "prove", uk: "доводити" },
  { en: "public", uk: "громадський" },
  { en: "pull", uk: "тягнути" },
  { en: "push", uk: "штовхати" },
  { en: "put", uk: "класти" },
  { en: "quality", uk: "якість" },
  { en: "question", uk: "питання" },
  { en: "quick", uk: "швидкий" },
  { en: "quiet", uk: "тихий" },
  { en: "quite", uk: "досить" },
  { en: "radio", uk: "радіо" },
  { en: "rain", uk: "дощ" },
  { en: "raise", uk: "піднімати" },
  { en: "reach", uk: "досягати" },
  { en: "read", uk: "читати" },
  { en: "ready", uk: "готовий" },
  { en: "real", uk: "реальний" },
  { en: "really", uk: "дійсно" },
  { en: "reason", uk: "причина" },
  { en: "receive", uk: "отримувати" },
  { en: "record", uk: "запис" },
  { en: "remember", uk: "пам’ятати" },
  { en: "repeat", uk: "повторювати" },
  { en: "report", uk: "звіт / повідомляти" },
  { en: "rest", uk: "відпочинок / решта" },
  { en: "restaurant", uk: "ресторан" },
  { en: "result", uk: "результат" },
  { en: "return", uk: "повертатися" },
  { en: "rich", uk: "багатий" },
  { en: "ride", uk: "їздити (верхи)" },
  { en: "right", uk: "правий / правильний" },
  { en: "ring", uk: "кільце / дзвонити" },
  { en: "rise", uk: "підніматися" },
  { en: "river", uk: "річка" },
  { en: "road", uk: "дорога" },
  { en: "round", uk: "круглий" },
  { en: "rule", uk: "правило" },
  { en: "run", uk: "бігти" },
  { en: "sad", uk: "сумний" },
  { en: "safe", uk: "безпечний" },
  { en: "same", uk: "той самий" },
  { en: "sand", uk: "пісок" },
  { en: "save", uk: "зберігати / рятувати" },
  { en: "say", uk: "сказати" },
  { en: "school", uk: "школа" },
  { en: "science", uk: "наука" },
  { en: "sea", uk: "море" },
  { en: "season", uk: "сезон" },
  { en: "seat", uk: "сидіння / місце" },
  { en: "second", uk: "секунда / другий" },
  { en: "section", uk: "секція / розділ" },
  { en: "see", uk: "бачити" },
  { en: "seem", uk: "здаватися" },
  { en: "sell", uk: "продавати" },
  { en: "send", uk: "надсилати" },
  { en: "sentence", uk: "речення" },
  { en: "serve", uk: "обслуговувати" },
  { en: "service", uk: "сервіс / послуга" },
  { en: "set", uk: "набір / встановлювати" },
  { en: "seven", uk: "сім" },
  { en: "several", uk: "декілька" },
  { en: "shake", uk: "трясти / потискати" },
  { en: "shape", uk: "форма" },
  { en: "share", uk: "ділитися / частка" },
  { en: "she", uk: "вона" },
  { en: "ship", uk: "корабель" },
  { en: "shoe", uk: "туфля" },
  { en: "shop", uk: "магазин" },
  { en: "short", uk: "короткий" },
  { en: "should", uk: "слід" },
  { en: "show", uk: "показувати" },
  { en: "side", uk: "бік / сторона" },
  { en: "sign", uk: "знак / підпис" },
  { en: "simple", uk: "простий" },
  { en: "since", uk: "з того часу / оскільки" },
  { en: "sing", uk: "співати" },
  { en: "single", uk: "один / неодружений" },
  { en: "sister", uk: "сестра" },
  { en: "sit", uk: "сидіти" },
  { en: "six", uk: "шість" },
  { en: "size", uk: "розмір" },
  { en: "skill", uk: "навичка" },
  { en: "sleep", uk: "спати" },
  { en: "slow", uk: "повільний" },
  { en: "small", uk: "маленький" },
  { en: "smile", uk: "посмішка / посміхатися" },
  { en: "snow", uk: "сніг" },
  { en: "so", uk: "так / тому" },
  { en: "some", uk: "деякі" },
  { en: "somebody", uk: "хтось" },
  { en: "someone", uk: "хтось" },
  { en: "something", uk: "щось" },
  { en: "sometimes", uk: "іноді" },
  { en: "son", uk: "син" },
  { en: "song", uk: "пісня" },
  { en: "soon", uk: "скоро" },
  { en: "sorry", uk: "вибач" },
  { en: "sound", uk: "звук" },
  { en: "south", uk: "південь" },
  { en: "space", uk: "простір / космос" },
  { en: "speak", uk: "говорити" },
  { en: "special", uk: "особливий" },
  { en: "spell", uk: "вимовляти по літерах" },
  { en: "spend", uk: "витрачати" },
  { en: "sport", uk: "спорт" },
  { en: "spring", uk: "весна / джерело" },
  { en: "stand", uk: "стояти" },
  { en: "star", uk: "зірка" },
  { en: "start", uk: "починати" },
  { en: "station", uk: "станція" },
  { en: "stay", uk: "залишатися" },
  { en: "step", uk: "крок" },
  { en: "still", uk: "все ще" },
  { en: "stop", uk: "зупиняти" },
  { en: "store", uk: "магазин" },
  { en: "story", uk: "історія / розповідь" },
  { en: "street", uk: "вулиця" },
  { en: "strong", uk: "сильний" },
  { en: "student", uk: "студент" },
  { en: "study", uk: "вивчати" },
  { en: "subject", uk: "предмет / тема" },
  { en: "success", uk: "успіх" },
  { en: "such", uk: "такий" },
  { en: "summer", uk: "літо" },
  { en: "sun", uk: "сонце" },
  { en: "support", uk: "підтримка" },
  { en: "sure", uk: "впевнений" },
  { en: "surprise", uk: "сюрприз / дивувати" },
  { en: "sweet", uk: "солодкий" },
  { en: "swim", uk: "плавати" },
  { en: "table", uk: "стіл" },
  { en: "take", uk: "брати" },
  { en: "talk", uk: "розмовляти" },
  { en: "tall", uk: "високий" },
  { en: "teach", uk: "викладати" },
  { en: "teacher", uk: "вчитель" },
  { en: "team", uk: "команда" },
  { en: "tell", uk: "розповідати" },
  { en: "ten", uk: "десять" },
  { en: "test", uk: "тест" },
  { en: "than", uk: "ніж" },
  { en: "thank", uk: "дякувати" },
  { en: "that", uk: "той" },
  { en: "the", uk: "артикль the" },
  { en: "their", uk: "їхній" },
  { en: "them", uk: "їх" },
  { en: "then", uk: "потім" },
  { en: "there", uk: "там" },
  { en: "these", uk: "ці" },
  { en: "they", uk: "вони" },
  { en: "thing", uk: "річ" },
  { en: "think", uk: "думати" },
  { en: "third", uk: "третій" },
  { en: "this", uk: "цей" },
  { en: "those", uk: "ті" },
  { en: "three", uk: "три" },
  { en: "through", uk: "через" },
  { en: "time", uk: "час" },
  { en: "to", uk: "до" },
  { en: "today", uk: "сьогодні" },
  { en: "together", uk: "разом" },
  { en: "tomorrow", uk: "завтра" },
  { en: "tonight", uk: "сьогодні ввечері" },
  { en: "too", uk: "також / занадто" },
  { en: "town", uk: "місто" },
  { en: "train", uk: "поїзд / тренувати" },
  { en: "travel", uk: "подорожувати" },
  { en: "tree", uk: "дерево" },
  { en: "true", uk: "правдивий" },
  { en: "try", uk: "намагатися" },
  { en: "turn", uk: "повертати" },
  { en: "two", uk: "два" },
  { en: "under", uk: "під" },
  { en: "understand", uk: "розуміти" },
  { en: "unit", uk: "одиниця" },
  { en: "until", uk: "до" },
  { en: "up", uk: "вгору" },
  { en: "us", uk: "нас" },
  { en: "use", uk: "використовувати" },
  { en: "usual", uk: "звичайний" },
  { en: "very", uk: "дуже" },
  { en: "village", uk: "село" },
  { en: "visit", uk: "відвідувати" },
  { en: "voice", uk: "голос" },
  { en: "wait", uk: "чекати" },
  { en: "walk", uk: "гуляти" },
  { en: "want", uk: "хотіти" },
  { en: "warm", uk: "теплий" },
  { en: "wash", uk: "мити" },
  { en: "watch", uk: "дивитися / годинник" },
  { en: "water", uk: "вода" },
  { en: "way", uk: "шлях / спосіб" },
  { en: "we", uk: "ми" },
  { en: "wear", uk: "носити (одяг)" },
  { en: "week", uk: "тиждень" },
  { en: "welcome", uk: "ласкаво просимо" },
  { en: "well", uk: "добре / криниця" },
  { en: "west", uk: "захід" },
  { en: "what", uk: "що" },
  { en: "when", uk: "коли" },
  { en: "where", uk: "де" },
  { en: "which", uk: "який" },
  { en: "while", uk: "поки" },
  { en: "white", uk: "білий" },
  { en: "who", uk: "хто" },
  { en: "why", uk: "чому" },
  { en: "wife", uk: "дружина" },
  { en: "will", uk: "буде" },
  { en: "win", uk: "вигравати" },
  { en: "wind", uk: "вітер" },
  { en: "window", uk: "вікно" },
  { en: "winter", uk: "зима" },
  { en: "with", uk: "з" },
  { en: "woman", uk: "жінка" },
  { en: "word", uk: "слово" },
  { en: "work", uk: "працювати" },
  { en: "world", uk: "світ" },
  { en: "write", uk: "писати" },
  { en: "wrong", uk: "неправильний" },
  { en: "year", uk: "рік" },
  { en: "yellow", uk: "жовтий" },
  { en: "yes", uk: "так" },
  { en: "yesterday", uk: "вчора" },
  { en: "you", uk: "ти / ви" },
  { en: "zoo", uk: "зоопарк" }
];















